version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: autobackcom-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: autobackcom-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
volumes:
  mongo_data:
